spring:
  data:
    mongodb:
      uri: mongodb://app_user:Test_1234@localhost:27017/dependency_tracker?authSource=admin


logging.level:
  root: INFO
  org.akj.test.tracker: DEBUG
  org.springframework.web: DEBUG
  org.springframework.data.mongodb: DEBUG
  org.springframework.boot.autoconfigure.mongo: DEBUG
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG
