spring:
  application:
    name: dependency-tracker
  task:
    scheduling:
      pool:
        size: 10


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PWD:}
    key-path: files/local_encryption_key.txt
server:
  port: 8080
  servlet:
    context-path: /${spring.application.name:}
